spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/nhom611}

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info
#     mongodb:
